"""Four-layer routing evidence: official, benchmark, community, production.

Offline by default. The only thing here with a route to a live decision is
:mod:`router_evidence_core.lcb`, and it returns an empty adjustment map unless
a feature flag is on. Everything else — the layer store, the priors, the
hierarchical posterior, the replay harness, the exploration policy — computes
numbers for people to read.
"""

from .betamath import beta_mean, beta_quantile, regularized_incomplete_beta
from .calibration import BRIDGES, CalibrationBridge, bridge_between, may_pool
from .community import CommunityAggregate, CommunityAggregator
from .coverage import (
    ContaminationFinding,
    CoverageReport,
    EvidenceConflict,
    ModelCoverage,
    attach_community_effective_sizes,
    audit_contamination,
    build_coverage,
    find_conflicts,
)
from .exploration import (
    ExplorationConstraints,
    ExplorationPolicy,
    ExplorationSimulation,
    ExplorationVerdict,
)
from .ingest import EvidenceIngestor, IngestReport, Rejection, content_hash, deduplicate
from .keys import (
    ConditionBucket,
    EvidenceKey,
    MetricScale,
    ReferenceMode,
    ScaleKind,
    Scenario,
    TaskType,
)
from .layers import (
    DEFAULT_PRIOR_STRENGTHS,
    EXTERNAL_LAYERS,
    EvidenceLayer,
    LayerIsolationError,
    PriorStrength,
    SourceClassMismatch,
    layer_for_source_type,
)
from .lcb import (
    CandidateModel,
    ConservativeLcbBuilder,
    LcbAdjustments,
    LcbDecision,
    LcbSettings,
    PosteriorLookup,
    merge_with_baseline,
)
from .observations import (
    OUTCOME_SCALES,
    OUTCOME_TO_ROUTER_DIMENSION,
    OutcomeName,
    ProductionObservation,
    PromptComplexity,
)
from .posterior import (
    CostLatencySummary,
    ExternalPriorContribution,
    HierarchicalPosteriorEngine,
    PosteriorLevel,
    PosteriorRecord,
    PosteriorRun,
    quarantine_unversioned,
)
from .priors import (
    KNOWN_EXTERNAL_SCALES,
    LayerPrior,
    RefusedContribution,
    build_layer_priors,
    prior_summary,
    production_contributions,
)
from .records import (
    PRIOR_ELIGIBLE_CREDIBILITY,
    PRIOR_ELIGIBLE_MATCHES,
    BenchmarkRecord,
    CommunityRecord,
    ExternalRecord,
    Measurement,
    ModelBinding,
    OfficialRecord,
    Provenance,
    SampleStatistics,
)
from .replay import (
    IntervalCoverage,
    PolicyResult,
    ReplayContext,
    ReplayHarness,
    ReplayResult,
    fixed_order_policy,
)
from .routing_context import (
    router_conditions,
    router_reference_mode,
    router_scenario,
    router_task_type,
)
from .store import (
    DEFAULT_EVIDENCE_ROOT,
    LAYER_FILENAMES,
    BenchmarkLayerFile,
    CommunityLayerFile,
    EvidenceLayerStore,
    LayerConflict,
    LayerGap,
    LayerSnapshot,
    OfficialLayerFile,
    write_layer_file,
)

__all__ = [
    "BRIDGES",
    "DEFAULT_EVIDENCE_ROOT",
    "DEFAULT_PRIOR_STRENGTHS",
    "EXTERNAL_LAYERS",
    "KNOWN_EXTERNAL_SCALES",
    "LAYER_FILENAMES",
    "OUTCOME_SCALES",
    "OUTCOME_TO_ROUTER_DIMENSION",
    "PRIOR_ELIGIBLE_CREDIBILITY",
    "PRIOR_ELIGIBLE_MATCHES",
    "BenchmarkLayerFile",
    "BenchmarkRecord",
    "CalibrationBridge",
    "CandidateModel",
    "CommunityAggregate",
    "CommunityAggregator",
    "CommunityLayerFile",
    "CommunityRecord",
    "ConditionBucket",
    "ConservativeLcbBuilder",
    "ContaminationFinding",
    "CostLatencySummary",
    "CoverageReport",
    "EvidenceConflict",
    "EvidenceIngestor",
    "EvidenceKey",
    "EvidenceLayer",
    "EvidenceLayerStore",
    "ExplorationConstraints",
    "ExplorationPolicy",
    "ExplorationSimulation",
    "ExplorationVerdict",
    "ExternalPriorContribution",
    "ExternalRecord",
    "HierarchicalPosteriorEngine",
    "IngestReport",
    "IntervalCoverage",
    "LayerConflict",
    "LayerGap",
    "LayerIsolationError",
    "LayerPrior",
    "LayerSnapshot",
    "LcbAdjustments",
    "LcbDecision",
    "LcbSettings",
    "Measurement",
    "MetricScale",
    "ModelBinding",
    "ModelCoverage",
    "OfficialLayerFile",
    "OfficialRecord",
    "OutcomeName",
    "PolicyResult",
    "PosteriorLevel",
    "PosteriorLookup",
    "PosteriorRecord",
    "PosteriorRun",
    "PriorStrength",
    "ProductionObservation",
    "PromptComplexity",
    "Provenance",
    "ReferenceMode",
    "RefusedContribution",
    "Rejection",
    "ReplayContext",
    "ReplayHarness",
    "ReplayResult",
    "SampleStatistics",
    "ScaleKind",
    "Scenario",
    "SourceClassMismatch",
    "TaskType",
    "attach_community_effective_sizes",
    "audit_contamination",
    "beta_mean",
    "beta_quantile",
    "bridge_between",
    "build_coverage",
    "build_layer_priors",
    "content_hash",
    "deduplicate",
    "find_conflicts",
    "fixed_order_policy",
    "layer_for_source_type",
    "may_pool",
    "merge_with_baseline",
    "prior_summary",
    "production_contributions",
    "quarantine_unversioned",
    "regularized_incomplete_beta",
    "router_conditions",
    "router_reference_mode",
    "router_scenario",
    "router_task_type",
    "write_layer_file",
]
